[2023-06-21T12:00:37.946+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task scheduled__2023-06-20T12:00:00+00:00 [queued]>
[2023-06-21T12:00:37.954+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task scheduled__2023-06-20T12:00:00+00:00 [queued]>
[2023-06-21T12:00:37.954+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T12:00:37.954+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-21T12:00:37.954+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T12:00:37.968+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): hello_task> on 2023-06-20 12:00:00+00:00
[2023-06-21T12:00:37.971+0000] {standard_task_runner.py:55} INFO - Started process 106 to run task
[2023-06-21T12:00:37.973+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_task', 'scheduled__2023-06-20T12:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpunrypir5']
[2023-06-21T12:00:37.975+0000] {standard_task_runner.py:83} INFO - Job 204: Subtask hello_task
[2023-06-21T12:00:38.552+0000] {task_command.py:389} INFO - Running <TaskInstance: hello_world.hello_task scheduled__2023-06-20T12:00:00+00:00 [running]> on host hello-world-hello-task-f2ddaac28dba43c3ae09c7e838970121
[2023-06-21T12:00:39.435+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:58 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-21T12:00:39.437+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:64 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-21T12:00:39.438+0000] {pod_generator.py:424} WARNING - Model file /opt/***/pod_templates/pod_template.yaml does not exist
[2023-06-21T12:00:39.476+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-20T12:00:00+00:00
[2023-06-21T12:00:39.476+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 11, in print_hello
    with open("/data/hello_world.txt", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/hello_world.txt'
[2023-06-21T12:00:39.487+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_task, execution_date=20230620T120000, start_date=20230621T120037, end_date=20230621T120039
[2023-06-21T12:00:39.498+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 204 for task hello_task ([Errno 2] No such file or directory: '/data/hello_world.txt'; 106)
[2023-06-21T12:00:39.514+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-21T12:00:39.547+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
